import '@app/global.scss'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar'
import cn from '@utils/cn'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}


const RootLayout = ({ children }: { children: ReactNode }): ReactNode => (
  <html lang="en">
    <body className={cn('min-h-screen antialiased bg-grainy', inter.className)}>
      <NavBar />
      {children}
    </body>
  </html>
)


export default RootLayout
