import '@app/global.scss'
import { Inter } from 'next/font/google'
import cn from '@utils/cn'
import type { Metadata } from 'next'
import type { JSX, ReactNode } from 'react'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}


const RootLayout = ({ children }: { children: ReactNode }): JSX.Element => (
  <html lang="en">
    <body className={cn('min-h-screen antialiased', inter.className)}>{children}</body>
  </html>
)


export default RootLayout
